import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generatePDF = (toolName, target, data) => {
    const doc = new jsPDF();
    const date = new Date().toLocaleString();

    // -- HEADER --
    // Background for header
    doc.setFillColor(5, 5, 5); // #050505
    doc.rect(0, 0, 210, 40, 'F');

    // Logo / Title
    doc.setTextColor(0, 255, 136); // #00ff88
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('BYTEGUARD', 15, 20);

    doc.setFontSize(10);
    doc.setTextColor(200, 200, 200);
    doc.text('ENTERPRISE SECURITY REPORT', 15, 28);

    // Report Info (Right side)
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text(`DATE: ${date}`, 195, 20, { align: 'right' });
    doc.text(`TARGET: ${target}`, 195, 28, { align: 'right' });

    // -- CONTENT --
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text(`${toolName} Analysis`, 15, 55);

    // Disclaimer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('CONFIDENTIAL: This report contains sensitive security information.', 15, 62);

    // Dynamic Content based on Tool
    if (toolName === 'Port Scanner') {
        const tableData = data.map(row => [
            row.port,
            row.service,
            row.status.toUpperCase()
        ]);

        autoTable(doc, {
            startY: 70,
            head: [['PORT', 'SERVICE', 'STATUS']],
            body: tableData,
            headStyles: { fillColor: [0, 0, 0], textColor: [0, 255, 136] },
            alternateRowStyles: { fillColor: [240, 240, 240] },
            styles: { fontSize: 10, cellPadding: 4 }
        });
    } else if (toolName === 'Password Auditor') {
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);

        doc.text(`Entropy Score: ${data.entropy.toFixed(2)} bits`, 15, 80);
        doc.text(`Security Level: ${data.score.toFixed(0)}/100`, 15, 90);

        doc.text('Estimated Crack Times:', 15, 110);

        const timesData = [
            ['Online Attack', data.times.online],
            ['Offline (CPU)', data.times.cpu],
            ['Offline (GPU)', data.times.gpu],
            ['Supercomputer', data.times.cluster]
        ];

        autoTable(doc, {
            startY: 115,
            head: [['Attack Scenario', 'Estimated Time']],
            body: timesData,
            headStyles: { fillColor: [0, 0, 0], textColor: [0, 255, 136] },
            styles: { fontSize: 10 }
        });
    }

    // -- FOOTER --
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by ByteGuard Enterprise Platform', 105, 290, { align: 'center' });
    }

    // Save
    doc.save(`ByteGuard_Report_${toolName.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};
